source 'https://rubygems.org'
group :development do
  gem 'json', '~> 1.7.7'
  gem 'sinatra'
  gem 'sprockets'
  gem 'sass'
  gem 'eco'
  gem 'thin'
  gem 'uglifier'
  gem 'sinatra-contrib'
  gem 'sinatra-asset-pipeline', :path => '~/Projects/sinatra-asset-pipeline'
  #gem 'sinatra-asset-pipeline', :git => 'https://github.com/joshuairl/sinatra-asset-pipeline.git'
  gem 'sprockets-helpers'
  gem 'sprockets-sass'
  gem 'coffee-script'
  gem 'sprite-factory'
  gem 'rmagick'
  gem 'chunky_png'
end