source 'https://rubygems.org'
gem 'sinatra'
gem 'sprockets'
gem 'sinatra-sprockets', :path => '/Users/joshua/Projects/sinatra-sprockets'
gem 'therubyracer'
gem 'sprockets-less', :git => 'https://github.com/viddo/sprockets-less.git'
gem 'less'
gem 'coffee-script'